- name: Create EC2
  hosts: localhost
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-0a716b1b175b22097
    instance:
    - mongodb
    - redis
  tasks:
    - name: Create EC2 Instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        region: "us-east-1"
        tags:
          Name: "{{ item }}"
      loop: "{{ instance }}"
      register: ec2_output

    # - name: Print EC2 Output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_output }}"

    - name: Print EC2 Public IP
      ansible.builtin.debug: 
        msg: "{{ item.instances[*].public_ip_address }}"
      loop: "{{ ec2_output.results }}"

    - name: Print EC2 Private IP
      ansible.builtin.debug: 
        msg: "{{ item.instances[*].private_ip_address }}"
      loop: "{{ ec2_output.results }}"
